name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #clone repository
      - uses: actions/setup-node@v2 # install node
        with:
          node-version: '14'
      - run: yarn install # install project dependencies
      - run: yarn test --watchAll=false # test code
      - run: yarn build # build application
      - run: ls -la
      - run: ls -la build/
      - uses: akhileshns/heroku-deploy@v3.12.12 # deploy to heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "./"
